CREATE TABLE IF NOT EXISTS USER (
id int(11) NOT NULL AUTO_INCREMENT,
name varchar(90) DEFAULT NULL,
age int(3) DEFAULT NULL,
PRIMARY KEY (id)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

INSERT INTO user (id, name, age) VALUES
(1, "Thais", 18);
COMMIT; 
